query commentGet($commentGetInput: CommentGetInput!) {
  commentGet(commentGetInput: $commentGetInput) {
    __typename
    id
    body
    createdAt
    author {
      __typename
      id
      profileImage
      name
      createdAt
    }
    parentId
    parent {
      __typename
      id
      createdAt
      parentId
      body
      author {
        __typename
        id
        profileImage
        name
        createdAt
      }
    }
    children {
      __typename
      id
      body
      createdAt
      author {
        __typename
        id
        profileImage
        name
        createdAt
      }
      children {
        __typename
        id
        body
        createdAt
        author {
          __typename
          id
          profileImage
          name
          createdAt
        }
      }
      parentId
    }
  }
}
