query commentGet($commentGetInput: CommentGetInput!) {
  commentGet(commentGetInput: $commentGetInput) {
    __typename
    author {
      __typename
      id
      profileImage
      name
      createdAt
    }
    body
    createdAt
    id
    parentId
    parent {
      __typename
      id
      parentId
      body
      author {
        __typename
        id
        profileImage
        name
        createdAt
      }
      createdAt
      id
    }
    children {
      id
    }
  }
}
