export enum ActionType {
  USER_LOGIN = "USER_LOGIN",
  USER_SIGN_OUT = "USER_SIGN_OUT",
  USER_SET = "USER_SET",
  SET_USER_FEED = "SET_USER_FEED",
  ADD_USER_POST = "ADD_USER_POST",
  VOTE_POST = "VOTE_POST",
  SET_POST = "SET_POST",
}
