query feedGet($feedGetInput: FeedGetInput!) {
  feedGet(feedGetInput: $feedGetInput) {
    id
    body
    createdAt
    userVoteStatus
    author {
      id
      name
      profileImage
      createdAt
    }
    comments {
      id
      parentId
      body
      createdAt
      author {
        id
        name
        profileImage
        createdAt
      }
    }
    score
  }
}
