query feedGet($feedGetInput: FeedGetInput!) {
  feedGet(feedGetInput: $feedGetInput) {
    id
    body
    createdAt
    upvotes
    downvotes
    userVoteStatus
    authorId
    authorName
    authorImage
    commentCount
  }
}
