query feedGet($feedGetInput: FeedGetInput!) {
  feedGet(feedGetInput: $feedGetInput) {
    __typename
    id
    body
    createdAt
    userVoteStatus
    score
    author {
      __typename
      id
      name
      profileImage
      createdAt
      phoneNumber
    }
    comments {
      __typename
      id
      body
      createdAt
      author {
        __typename
        id
        profileImage
        name
        createdAt
        phoneNumber
      }
      parentId
      children {
        id
      }
    }
  }
}
