query postGetAll($postGetAllInput: PostGetAllInput!) {
  postGetAll(postGetAllInput: $postGetAllInput) {
    id
    body
    createdAt
    author {
      phoneNumber
      profile {
        id
        profileImage
      }
    }
  }
}
