mutation postCreate($postCreateInput: PostCreateInput!) {
  postCreate(postCreateInput: $postCreateInput) {
    id
    body
    createdAt
    latitude
    longitude
    author {
      id
      profileImage
      createdAt
      name
    }
  }
}
