mutation postCreate($postCreateInput: PostCreateInput!) {
  postCreate(postCreateInput: $postCreateInput) {
    __typename
    id
    body
    createdAt
    latitude
    longitude
    author {
      __typename
      id
      profileImage
      createdAt
      name
      phoneNumber
    }
  }
}
