query postGet($postGetInput: PostGetInput!) {
  postGet(postGetInput: $postGetInput) {
    __typename
    id
    body
    createdAt
    userVoteStatus
    author {
      __typename
      id
      name
      profileImage
      createdAt
    }
    comments {
      __typename
      author {
        __typename
        id
        profileImage
        name
        createdAt
      }
      body
      createdAt
      id
      parentId
      parent {
        __typename
        id
        parentId
        body
        author {
          __typename
          id
          name
          profileImage
          createdAt
        }
        createdAt
        id
      }
      children {
        id
      }
    }
    score
  }
}
